USE ROLE ACCOUNTADMIN;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Hands-on Roleを作成
CREATE ROLE COCO_HANDS_ON_ROLE;

-- Git連携のため、API統合を作成する
CREATE OR REPLACE API INTEGRATION git_api_coco_hands_on_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-chtan/', 'https://github.com/snow-jp-handson-org/')
  ENABLED = TRUE;

-- 必要であれば仮想ウェアハウスを作成する
-- CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- Cortex Codeハンズオン参加者ロールに必要な権限を付与
GRANT USAGE ON INTEGRATION git_api_coco_hands_on_integration TO ROLE COCO_HANDS_ON_ROLE;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE COCO_HANDS_ON_ROLE;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE COCO_HANDS_ON_ROLE;

--GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COCO_HANDS_ON_ROLE;
